variable "project" {}
variable "location" {}
variable "k8s_name" {}
variable "k8s_enable_kubernetes_alpha" {}
variable "k8s_enable_legacy_abac" {}
variable "k8s_network" {}
variable "k8s_network_policy_enabled" {}
variable "k8s_private_cluster_config" {}
variable "k8s_ip_policy_enabled" {}
variable "k8s_ip_policy" {}
variable "master_authorized_networks_config" {}
variable "k8s_network_policy_config_disabled" {}
variable "k8s_http_load_balancing_disabled" {}
variable "k8s_username" {}
variable "k8s_password" {}
variable "k8s_certificate" {}
variable "k8s_enable_binary_auth" {}
variable "k8s_pod_security_enabled" {}
variable "k8s_db_encryption" {}
variable "k8s_monitoring_service" {}
variable "k8s_logging_service" {}
variable "k8s_resource_labels" {}
variable "k8s_node_count" {}
variable "node_locations" {}
variable "k8s_image_type" {}
variable "k8s_preemptible" {}
variable "k8s_machine_type" {}
variable "enable_intranode_visibility" {}
variable "enable_network_egress_metering" {}
variable "k8s_metadata" {}
