variable "project" {}
variable "location" {}

variable "vm_name" {}
variable "machine_type" {}
variable "zone" {}
variable "vm_tags" {}
variable "vm_image" {}
variable "scheduling_enabled" {}
variable "scheduling_preemptible" {}
variable "scheduling_on_host_maintenance" {}
variable "scheduling_automatic_restart" {}
variable "network" {}
variable "subnetwork" {}
variable "vm_access_config" {}
variable "email" {}
variable "scopes" {}
variable "can_ip_forward" {}
variable "vm_metadata" {}
variable "metadata_startup_script" {}
variable "labels" {}