variable "sql_server_rg" {}
variable "sql_server_name" {}
variable "sql_sec_policy_state" {}
variable "sql_sec_policy_endpoint" {}
variable "sql_sec_policy_access_key" {}
variable "sql_sec_policy_disabled_alerts" {}
variable "sql_sec_policy_retention" {}
variable "sql_sec_email_account_admins" {}
variable "sql_sec_email_addresses" {}
