variable "name" {}
variable "availability_zones" {}
variable "security_groups" {}
variable "logging_enabled" {}
variable "bucket" {}
variable "bucket_prefix" {}
variable "log_interval" {}
variable "listener" {}
variable "healthy_threshold" {}
variable "unhealthy_threshold" {}
variable "timeout" {}
variable "target" {}
variable "check_interval" {}
variable "instances" {}
variable "cross_zone_load_balancing" {}
variable "idle_timeout" {}
variable "connection_draining" {}
variable "connection_draining_timeout" {}
