variable "acr_webhook_name" {}
variable "acr_webhook_rg" {}
variable "acr_webhook_registry" {}
variable "location" {}
variable "acr_webhook_service_uri" {}
variable "acr_webhook_status" {}
variable "acr_webhook_scope" {}
variable "acr_webhook_actions" {}
variable "acr_webhook_custom_headers" {}
