# This is a basic workflow to help you get started with Actions

name: Prancer SCA

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell  
      - name: Install Prancer
        run: |
          pip3 install -U prancer-basic
          
      - name: Install opa 
        run: |
          echo "opa and helm binariees required, helm is packaged with ubuntu, install opa only"
          curl -L -o /usr/local/bin/opa https://openpolicyagent.org/downloads/v0.36.1/opa_linux_amd64_static
          chmod 755 /usr/local/bin/opa
          echo "opa binary path..."
          which opa
          echo "helm binary path..."
          which helm
          
      - name: Run Prancer
        run: |
          export APITOKEN=${{ secrets.APITOKEN }}
          export GITTOKEN=${{ secrets.GITTOKEN }}
          prancer --db REMOTE --company prancer-liquware git_ent_terraform
